# Generated by Django 4.0.3 on 2022-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('adress', models.CharField(max_length=220)),
            ],
        ),
    ]
